### ISSUE TITLE
`END` keyword inside metadata

### ISSUE THREAD

**Issue by DecimalTurn** [serkonda7/vscode-vba#92]
### Description and Reproduction Steps

Currently, the syntax highlighting doesn't make the difference between the `End` keyword inside a sub procedure that ends the code execution and the `END` keyword that appears at the top of a class module (.cls).

```vba
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
```

### Current Behavior

`END` keyword is highlighted as a control keyword but not `BEGIN`.

![image](https://github.com/serkonda7/vscode-vba/assets/31558169/d9d03fac-57eb-426b-a944-82312b7f9b05)

### Expected Behavior

`BEGIN` and `END` should be both highlighted or neither should be.

### Additional Information

Note that I've already started working on something to fix this here by using a metadata scope:
https://github.com/DecimalTurn/vscode-vba/blob/metadata/syntaxes/vba.tmGrammar.yml

```yml
metadata:
    name: metadata.vba
    begin: "(?i)^\\s*(BEGIN)\\b"
    beginCaptures:
      '1':
        name: "keyword.metadata.vba"     
    end: "(END)"
    endCaptures":
      '0':
        name: "keyword.metadata.vba"
    patterns: 
      - include: "source.vba" 
```

However, I'm having a weird bug with the testing library. It's like endCaptures doesn't work. See https://github.com/PanAeon/vscode-tmgrammar-test/issues/44

I haven't got a reply regarding my issue yet, so I'm still not sure if I'm missing something, so any feedback would be appreciated.

### Environment details

OS: Windows 10
VS Code Version: 1.80.2
Extension Version: v0.9.2
